# Generated by Django 4.0.4 on 2022-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Patronymic', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=11)),
                ('Request', models.TextField(blank=True)),
                ('Sent_date', models.DateField(auto_now_add=True)),
                ('Accepted', models.BooleanField(default=False)),
                ('Accepted_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-Sent_date'],
            },
        ),
    ]
