# Generated by Django 4.0.4 on 2022-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_First_name', models.CharField(max_length=50)),
                ('Worker_Patronymic', models.CharField(max_length=50)),
                ('Worker_Last_name', models.CharField(max_length=50)),
                ('Worker_Position', models.CharField(max_length=100)),
            ],
        ),
    ]
